#
# FUnctional tests
#
# Copyright (C) 2016 Stas Kobzar <stas@modulis.ca>
#
set testcases {
  {"Usage message" "-h" "Usage: "}
}

global SKINNYCAT
foreach pattern $testcases {
  set msg    [lindex $pattern 0]
  set argv   [lindex $pattern 1]
  set output [lindex $pattern 2]
  pass "OK"
#  eval "spawn $SKINNYCAT $argv"

#  expect {
#    -re $output { pass $msg }
#    default     { fail $msg }
#  }
}
